import 'package:flutter/material.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk_flutter.dart';
import 'package:voxpollui/onboarding_page.dart';

class BoardinBes extends StatefulWidget {
  final String userId;
  BoardinBes({Key? key, required this.userId}) : super(key: key);
  @override
  _BoardinBesState createState() => _BoardinBesState();
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class _BoardinBesState extends State<BoardinBes> {  
  List<String> interests = [];

  List<bool> isSelected = List.generate(18, (_) => false);

  @override
  void initState() {
    super.initState();
    _fetchInterests();
  }

  Future<void> _fetchInterests() async {
    final ParseResponse response = await ParseObject('Interest').getAll();
    if (response.success && response.results != null) {
      setState(() {
        interests = response.results!.map((e) => e.get<String>('name') as String).toList();
      });
    } else {
      // Handle error
    }
  }

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          SizedBox(height: 50,),
        Text(
          'İlgi Alanları',
          style: TextStyle(
          color: Color(0xFF0C0C0C),
          fontSize: 40,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w600,
          height: 0,
          ),
        ),
        SizedBox(height: 20,),
        Text(
          '5 adet seçebilir ve profilinizden güncelleyebilirsiniz.',
          style: TextStyle(
          color: Color(0xFF0C0C0C),
          fontSize: 13,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w400,
          height: 0.08,
          ),
        ),
          Expanded(
            child: GridView.builder(
              padding: EdgeInsets.all(8),
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                crossAxisSpacing: 10,
                mainAxisSpacing: 10,
                childAspectRatio: 3,
              ),
              itemCount: interests.length,
              itemBuilder: (context, index) {
                return GestureDetector(
                  onTap: () {
                    setState(() {
                      isSelected[index] = !isSelected[index];
                    });
                  },
                  child: Container(
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      color: isSelected[index] ? Color(0xFF2355FF) : Colors.white,
                      border: Border.all(color: Colors.black54),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      interests[index],
                      style: TextStyle(
                        color: isSelected[index] ? Colors.white : Colors.black
                      ),  
                    ),
                  ),
                );
              },
            ),
          ),
          GestureDetector(
          onTap: () {
            Navigator.push(context, MaterialPageRoute(builder: (context) => OnboardingPage()));
          },
          child: Container(
            alignment: Alignment.bottomCenter,
            width: double.infinity,
            height: 49,
            margin: EdgeInsets.all(31), // Burası ekranın kenar boşluklarını ayarlar
            decoration: ShapeDecoration(
              color: Color(0xFF2355FF),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(5),
              ),
            ),
            child: Center(
              child: Text(
                'İleri',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 16,
                  fontFamily: 'Gilroy',
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ),
        ),
        ],
      ),
    );
  }
}

// class AreasOfInterest extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 428,
//           height: 926,
//           clipBehavior: Clip.antiAlias,
//           decoration: ShapeDecoration(
//             color: Colors.white,
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(32),
//             ),
//           ),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 36,
//                 top: 196,
//                 child: Text(
//                   '10 adet seçebilir ve profilinizden güncelleyebilirsiniz.',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 13,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w400,
//                     height: 0.08,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 133,
//                 child: Text(
//                   'İlgi Alanları',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 40,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w600,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 236,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 226,
//                 top: 236,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 301,
//                 child: Container(
//                   width: 167.01,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 301,
//                 child: Container(
//                   width: 171.16,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 365,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 365,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 430,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 430,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 495,
//                 child: Container(
//                   width: 167.01,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 495,
//                 child: Container(
//                   width: 171.16,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 559,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 559,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 624,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 624,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 689,
//                 child: Container(
//                   width: 167.01,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 689,
//                 child: Container(
//                   width: 171.16,
//                   height: 42,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 36,
//                 top: 753,
//                 child: Container(
//                   width: 167.01,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 225.84,
//                 top: 753,
//                 child: Container(
//                   width: 171.16,
//                   height: 43,
//                   decoration: ShapeDecoration(
//                     shape: RoundedRectangleBorder(
//                       side: BorderSide(width: 1, color: Color(0xFF0C0C0C)),
//                       borderRadius: BorderRadius.circular(5),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 90.94,
//                 top: 249,
//                 child: SizedBox(
//                   width: 60.17,
//                   height: 26,
//                   child: Text(
//                     'Politika',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 97.17,
//                 top: 637,
//                 child: SizedBox(
//                   width: 48.76,
//                   height: 26,
//                   child: Text(
//                     'Moda',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 82.64,
//                 top: 378,
//                 child: SizedBox(
//                   width: 74.69,
//                   height: 26,
//                   child: Text(
//                     'Teknoloji',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 95.09,
//                 top: 507,
//                 child: SizedBox(
//                   width: 45.64,
//                   height: 27,
//                   child: Text(
//                     'Doğa',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 96.13,
//                 top: 313,
//                 child: SizedBox(
//                   width: 43.57,
//                   height: 27,
//                   child: Text(
//                     'Tarih',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 59.82,
//                 top: 701,
//                 child: SizedBox(
//                   width: 118.26,
//                   height: 27,
//                   child: Text(
//                     'Sosyal Medya',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 97.17,
//                 top: 766,
//                 child: SizedBox(
//                   width: 42.53,
//                   height: 26,
//                   child: Text(
//                     'Gıda',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 79.53,
//                 top: 443,
//                 child: SizedBox(
//                   width: 79.88,
//                   height: 26,
//                   child: Text(
//                     'Otomotiv',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 87.83,
//                 top: 572,
//                 child: SizedBox(
//                   width: 64.32,
//                   height: 26,
//                   child: Text(
//                     'Sinema',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 292,
//                 top: 249,
//                 child: SizedBox(
//                   width: 39.42,
//                   height: 26,
//                   child: Text(
//                     'Spor',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 276.63,
//                 top: 637,
//                 child: SizedBox(
//                   width: 71.58,
//                   height: 26,
//                   child: Text(
//                     'Ekonomi',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 281.82,
//                 top: 378,
//                 child: SizedBox(
//                   width: 59.13,
//                   height: 26,
//                   child: Text(
//                     'Yazılım',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 293.23,
//                 top: 507,
//                 child: SizedBox(
//                   width: 41.49,
//                   height: 27,
//                   child: Text(
//                     'Bilim',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 289.08,
//                 top: 313,
//                 child: SizedBox(
//                   width: 46.68,
//                   height: 27,
//                   child: Text(
//                     'Müzik',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 281.82,
//                 top: 701,
//                 child: SizedBox(
//                   width: 59.13,
//                   height: 27,
//                   child: Text(
//                     'Girişim',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 262.11,
//                 top: 766,
//                 child: SizedBox(
//                   width: 100.62,
//                   height: 26,
//                   child: Text(
//                     'Dekorasyon',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 284.93,
//                 top: 443,
//                 child: SizedBox(
//                   width: 53.94,
//                   height: 26,
//                   child: Text(
//                     'Futbol',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 282.85,
//                 top: 572,
//                 child: SizedBox(
//                   width: 58.09,
//                   height: 26,
//                   child: Text(
//                     'E-Spor',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 0,
//                 top: 0,
//                 child: Container(
//                   width: 428,
//                   height: 47,
//                   clipBehavior: Clip.antiAlias,
//                   decoration: BoxDecoration(),
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 33,
//                         top: 14,
//                         child: Container(
//                           width: 54,
//                           height: 21,
//                           padding: const EdgeInsets.only(top: 1),
//                           decoration: ShapeDecoration(
//                             shape: RoundedRectangleBorder(
//                               borderRadius: BorderRadius.circular(24),
//                             ),
//                           ),
//                           child: Row(
//                             mainAxisSize: MainAxisSize.min,
//                             mainAxisAlignment: MainAxisAlignment.center,
//                             crossAxisAlignment: CrossAxisAlignment.center,
//                             children: [
//                               SizedBox(
//                                 width: 54,
//                                 height: 20,
//                                 child: Text(
//                                   '9:41',
//                                   textAlign: TextAlign.center,
//                                   style: TextStyle(
//                                     color: Color(0xFF010101),
//                                     fontSize: 17,
//                                     fontFamily: 'SF Pro Text',
//                                     fontWeight: FontWeight.w600,
//                                     height: 0.08,
//                                     letterSpacing: -0.41,
//                                   ),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                       Positioned(
//                         left: 318,
//                         top: 19,
//                         child: Container(
//                           width: 77.40,
//                           height: 13,
//                           child: Stack(
//                             children: [
//                               Positioned(
//                                 left: 50,
//                                 top: 0,
//                                 child: Container(
//                                   width: 27.40,
//                                   height: 13,
//                                   child: Stack(children: [
//                                   ,
//                                   ]),
//                                 ),
//                               ),
//                               Positioned(
//                                 left: 26,
//                                 top: 1,
//                                 child: Container(
//                                   width: 17,
//                                   height: 12,
//                                   decoration: BoxDecoration(
//                                     image: DecorationImage(
//                                       image: NetworkImage("https://via.placeholder.com/17x12"),
//                                       fit: BoxFit.fill,
//                                     ),
//                                   ),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 843,
//                 child: Container(
//                   width: 366,
//                   height: 49,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF2355FF),
//                     shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 202,
//                 top: 861,
//                 child: Text(
//                   'İleri',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 16,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w700,
//                     height: 0,
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }