import 'package:flutter/material.dart';
import 'package:voxpollui/boarding/boarding_iki.dart';

void main() {
  runApp(const BoardinBir());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class BoardinBir extends StatelessWidget {
  const BoardinBir({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
  width: 428,
  height: 926,
  clipBehavior: Clip.antiAlias,
  decoration: ShapeDecoration(
    color: Colors.white,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(32),
    ),
  ),
  child: Stack(
    children: [
      Positioned(
        left: 298,
        top: 517,
        child: Container(
          width: 260,
          height: 260,
          child: Stack(
            children: [
              Positioned(
                left: 130,
                top: 0,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.79),
                  child: Container(
                    width: 183.85,
                    height: 183.85,
                    decoration: ShapeDecoration(
                      color: Color(0xFF2355FF),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(47),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      Positioned(
        left: 44,
        top: 94,
        child: Container(
          width: 90,
          height: 90,
          decoration: ShapeDecoration(
            image: DecorationImage(
              image: AssetImage("assets/profilepicture.png"),
              fit: BoxFit.fill,
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 290,
        top: 148,
        child: Container(
          width: 69,
          height: 69,
          decoration: ShapeDecoration(
            image: DecorationImage(
              image: AssetImage("assets/profilepicture.png"),
              fit: BoxFit.fill,
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 149,
        top: 281,
        child: Container(
          width: 125,
          height: 125,
          decoration: ShapeDecoration(
            image: DecorationImage(
              image: AssetImage("assets/profilepicture.png"),
              fit: BoxFit.fill,
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 115,
        top: 263,
        child: Container(
          width: 13,
          height: 13,
          decoration: ShapeDecoration(
            color: Color(0xFFED3434),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 307,
        top: 94,
        child: Container(
          width: 18,
          height: 18,
          decoration: ShapeDecoration(
            color: Color(0xFF8FFF67),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 31,
        top: 61,
        child: Container(
          width: 26,
          height: 26,
          decoration: ShapeDecoration(
            color: Color(0xFFFF19CD),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 241,
        top: 272,
        child: Container(
          width: 153,
          height: 39,
          decoration: ShapeDecoration(
            color: Color(0xFF0C0C0C),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
        ),
      ),
      Positioned(
        left: 201,
        top: 168,
        child: Container(
          width: 101,
          height: 29,
          decoration: ShapeDecoration(
            color: Color(0xFF0C0C0C),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
        ),
      ),
      Positioned(
        left: 115,
        top: 86,
        child: Container(
          width: 129,
          height: 37,
          decoration: ShapeDecoration(
            color: Color(0xFF0C0C0C),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
        ),
      ),
      Positioned(
        left: 246,
        top: 276,
        child: Container(
          width: 31,
          height: 31,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 205,
        top: 171,
        child: Container(
          width: 23,
          height: 23,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 119,
        top: 90,
        child: Container(
          width: 29,
          height: 29,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
            ),
            shape: OvalBorder(),
          ),
        ),
      ),
      Positioned(
        left: 125,
        top: 96,
        child: Container(
          width: 17,
          height: 17,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
              fit: BoxFit.contain,
            ),
          ),
        ),
      ),
      Positioned(
        left: 253,
        top: 282,
        child: Container(
          width: 18,
          height: 18,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
              fit: BoxFit.contain,
            ),
          ),
        ),
      ),
      Positioned(
        left: 211,
        top: 177,
        child: Container(
          width: 11,
          height: 11,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
              fit: BoxFit.contain,
            ),
          ),
        ),
      ),
      Positioned(
        left: 286,
        top: 284,
        child: Container(
          width: 76,
          height: 4,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 155,
        top: 99,
        child: Container(
          width: 65,
          height: 3,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 236,
        top: 177,
        child: Container(
          width: 38,
          height: 3,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 286,
        top: 294,
        child: Container(
          width: 91,
          height: 4,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 155,
        top: 108,
        child: Container(
          width: 78,
          height: 3,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 236,
        top: 185,
        child: Container(
          width: 46,
          height: 3,
          decoration: ShapeDecoration(
            color: Color(0xFF323232),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 520,
        child: Text(
          'Bütün merak',
          style: TextStyle(
            color: Color(0xFF0C0C0C),
            fontSize: 40,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w300,
            height: 0,
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 564,
        child: Text(
          'ettiğiniz',
          style: TextStyle(
            color: Color(0xFF0C0C0C),
            fontSize: 40,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w300,
            height: 0,
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 608,
        child: Text(
          'cevaplar',
          style: TextStyle(
            color: Color(0xFF2355FF),
            fontSize: 40,
            fontFamily: 'Gilroy',
            fontWeight: FontWeight.w700,
            height: 0,
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 670,
        child: SizedBox(
          width: 265,
          height: 54,
          child: Text(
            'Merak ettiğiniz ankete katılabilir\n',
            style: TextStyle(
              color: Color(0xFF0C0C0C),
              fontSize: 16,
              fontFamily: 'Gilroy',
              fontWeight: FontWeight.w400,
              height: 0.07,
            ),
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 690,
        child: SizedBox(
          width: 265,
          height: 54,
          child: Text(
            'veya merak ettiğiniz bir anket \n',
            style: TextStyle(
              color: Color(0xFF0C0C0C),
              fontSize: 16,
              fontFamily: 'Gilroy',
              fontWeight: FontWeight.w400,
              height: 0.07,
            ),
          ),
        ),
      ),
      Positioned(
        left: 47,
        top: 710,
        child: SizedBox(
          width: 265,
          height: 54,
          child: Text(
            'başlatabilirsiniz.',
            style: TextStyle(
              color: Color(0xFF0C0C0C),
              fontSize: 16,
              fontFamily: 'Gilroy',
              fontWeight: FontWeight.w400,
              height: 0.07,
            ),
          ),
        ),
      ),
      // Positioned(
      //   left: 0,
      //   top: 0,
      //   child: Container(
      //     width: 428,
      //     height: 47,
      //     clipBehavior: Clip.antiAlias,
      //     decoration: BoxDecoration(),
      //     child: Stack(
      //       children: [
      //         Positioned(
      //           left: 33,
      //           top: 14,
      //           child: Container(
      //             width: 54,
      //             height: 21,
      //             padding: const EdgeInsets.only(top: 1),
      //             decoration: ShapeDecoration(
      //               shape: RoundedRectangleBorder(
      //                 borderRadius: BorderRadius.circular(24),
      //               ),
      //             ),
      //             child: Row(
      //               mainAxisSize: MainAxisSize.min,
      //               mainAxisAlignment: MainAxisAlignment.center,
      //               crossAxisAlignment: CrossAxisAlignment.center,
      //               children: [
      //                 SizedBox(
      //                   width: 54,
      //                   height: 20,
      //                   child: Text(
      //                     '9:41',
      //                     textAlign: TextAlign.center,
      //                     style: TextStyle(
      //                       color: Color(0xFF010101),
      //                       fontSize: 17,
      //                       fontFamily: 'SF Pro Text',
      //                       fontWeight: FontWeight.w600,
      //                       height: 0.08,
      //                       letterSpacing: -0.41,
      //                     ),
      //                   ),
      //                 ),
      //               ],
      //             ),
      //           ),
      //         ),
      //         Positioned(
      //           left: 318,
      //           top: 19,
      //           child: Container(
      //             width: 77.40,
      //             height: 13,
      //             child: Stack(
      //               children: [
      //                 Positioned(
      //                   left: 50,
      //                   top: 0,
      //                   child: Container(
      //                     width: 27.40,
      //                     height: 13,
      //                     child: Stack(children: [
                          
      //                     ]),
      //                   ),
      //                 ),
      //                 Positioned(
      //                   left: 26,
      //                   top: 1,
      //                   child: Container(
      //                     width: 17,
      //                     height: 12,
      //                     decoration: BoxDecoration(
      //                       image: DecorationImage(
      //                         image: NetworkImage("https://via.placeholder.com/17x12"),
      //                         fit: BoxFit.fill,
      //                       ),
      //                     ),
      //                   ),
      //                 ),
      //               ],
      //             ),
      //           ),
      //         ),
      //       ],
      //     ),
      //   ),
      // ),
      Align(
        alignment: Alignment.bottomCenter,
        child: Container(
          width: MediaQuery.of(context).size.width, // Ekran genişliği kadar genişlik ayarı
          child: ElevatedButton(
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (context) => BoardinIki()));
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Color(0xFF2355FF), // Arkaplan rengi
            ),
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                'İleri',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 16,
                  fontFamily: 'Gilroy',
                  fontWeight: FontWeight.w700,
                  height: 0,
                ),
              ),
            ),
          ),
        ),
      )
    ],
  ),
)
      ),
    );
  }
}

// class Login extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 428,
//           height: 926,
//           clipBehavior: Clip.antiAlias,
//           decoration: ShapeDecoration(
//             color: Colors.white,
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(32),
//             ),
//           ),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 298,
//                 top: 517,
//                 child: Container(
//                   width: 260,
//                   height: 260,
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 130,
//                         top: 0,
//                         child: Transform(
//                           transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.79),
//                           child: Container(
//                             width: 183.85,
//                             height: 183.85,
//                             decoration: ShapeDecoration(
//                               color: Color(0xFF2355FF),
//                               shape: RoundedRectangleBorder(
//                                 borderRadius: BorderRadius.circular(47),
//                               ),
//                             ),
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 44,
//                 top: 94,
//                 child: Container(
//                   width: 90,
//                   height: 90,
//                   decoration: ShapeDecoration(
//                     image: DecorationImage(
//                       image: AssetImage("assets/profilepicture.png"),
//                       fit: BoxFit.fill,
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 290,
//                 top: 148,
//                 child: Container(
//                   width: 69,
//                   height: 69,
//                   decoration: ShapeDecoration(
//                     image: DecorationImage(
//                       image: AssetImage("assets/profilepicture.png"),
//                       fit: BoxFit.fill,
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 149,
//                 top: 281,
//                 child: Container(
//                   width: 125,
//                   height: 125,
//                   decoration: ShapeDecoration(
//                     image: DecorationImage(
//                       image: AssetImage("assets/profilepicture.png"),
//                       fit: BoxFit.fill,
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 115,
//                 top: 263,
//                 child: Container(
//                   width: 13,
//                   height: 13,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFFED3434),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 307,
//                 top: 94,
//                 child: Container(
//                   width: 18,
//                   height: 18,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF8FFF67),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 61,
//                 child: Container(
//                   width: 26,
//                   height: 26,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFFFF19CD),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 241,
//                 top: 272,
//                 child: Container(
//                   width: 153,
//                   height: 39,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF0C0C0C),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(40),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 201,
//                 top: 168,
//                 child: Container(
//                   width: 101,
//                   height: 29,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF0C0C0C),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(40),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 115,
//                 top: 86,
//                 child: Container(
//                   width: 129,
//                   height: 37,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF0C0C0C),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(40),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 246,
//                 top: 276,
//                 child: Container(
//                   width: 31,
//                   height: 31,
//                   decoration: ShapeDecoration(
//                     gradient: LinearGradient(
//                       begin: Alignment(0.00, -1.00),
//                       end: Alignment(0, 1),
//                       colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 205,
//                 top: 171,
//                 child: Container(
//                   width: 23,
//                   height: 23,
//                   decoration: ShapeDecoration(
//                     gradient: LinearGradient(
//                       begin: Alignment(0.00, -1.00),
//                       end: Alignment(0, 1),
//                       colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 119,
//                 top: 90,
//                 child: Container(
//                   width: 29,
//                   height: 29,
//                   decoration: ShapeDecoration(
//                     gradient: LinearGradient(
//                       begin: Alignment(0.00, -1.00),
//                       end: Alignment(0, 1),
//                       colors: [Color(0xFF00A3D7), Color(0xFF2355FF)],
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 125,
//                 top: 96,
//                 child: Container(
//                   width: 17,
//                   height: 17,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
//                       fit: BoxFit.contain,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 253,
//                 top: 282,
//                 child: Container(
//                   width: 18,
//                   height: 18,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
//                       fit: BoxFit.contain,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 211,
//                 top: 177,
//                 child: Container(
//                   width: 11,
//                   height: 11,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://s3-alpha-sig.figma.com/img/d8ef/84f4/4616bd2596c3dce9e5a8b3ef45ac72bb?Expires=1702857600&Signature=o2svoUqNTG~Kb3xBpt5N-1tFawaPcDyytq~HrBBd~FDYS1aHbIyKW0DEC0FBJ7SdDW5bMxcTSIG79Q1QmaMvAz-0d3J9qzmMrf-Mr6bN7C1GRHQKBPYmGKva--hhNTK0wZkajl9aQJrwxdA~PhkL01CYW1M9dk2lVzoPX5udwaM0si~iNhr4~oXr4vWXn-Gu-Hg1u-X1LtKwLII2R9oGL1rOWUkLkeiq7lHpb3hkPc7EN48sRuK1Bhy0-qEA-GRupd1HKVHJgmUXVcFhsKQTBa~jnFxx6EfCpB5UamgwqHCX41sGTnUqte4ixXxFTQkITubHbzs4y3LemB2G6zNy7Q__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"),
//                       fit: BoxFit.contain,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 286,
//                 top: 284,
//                 child: Container(
//                   width: 76,
//                   height: 4,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 155,
//                 top: 99,
//                 child: Container(
//                   width: 65,
//                   height: 3,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 236,
//                 top: 177,
//                 child: Container(
//                   width: 38,
//                   height: 3,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 286,
//                 top: 294,
//                 child: Container(
//                   width: 91,
//                   height: 4,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 155,
//                 top: 108,
//                 child: Container(
//                   width: 78,
//                   height: 3,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 236,
//                 top: 185,
//                 child: Container(
//                   width: 46,
//                   height: 3,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF323232),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 47,
//                 top: 520,
//                 child: Text(
//                   'Bütün merak',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 40,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w300,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 47,
//                 top: 564,
//                 child: Text(
//                   'ettiğiniz',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 40,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w300,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 47,
//                 top: 608,
//                 child: Text(
//                   'cevaplar',
//                   style: TextStyle(
//                     color: Color(0xFF2355FF),
//                     fontSize: 40,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w700,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 47,
//                 top: 670,
//                 child: SizedBox(
//                   width: 265,
//                   height: 54,
//                   child: Text(
//                     'Merak ettiğiniz ankete katılabilir\nveya merak ettiğiniz bir anket \nbaşlatabilirsiniz.',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w400,
//                       height: 0.07,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 843,
//                 child: Container(
//                   width: 366,
//                   height: 49,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF2355FF),
//                     shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 202,
//                 top: 861,
//                 child: Text(
//                   'İleri',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 16,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w700,
//                     height: 0,
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }


/*              // Positioned(
              //   left: 0,
              //   top: 0,
              //   child: Container(
              //     width: 428,
              //     height: 47,
              //     clipBehavior: Clip.antiAlias,
              //     decoration: BoxDecoration(),
              //     child: Stack(
              //       children: [
              //         Positioned(
              //           left: 33,
              //           top: 14,
              //           child: Container(
              //             width: 54,
              //             height: 21,
              //             padding: const EdgeInsets.only(top: 1),
              //             decoration: ShapeDecoration(
              //               shape: RoundedRectangleBorder(
              //                 borderRadius: BorderRadius.circular(24),
              //               ),
              //             ),
              //             child: Row(
              //               mainAxisSize: MainAxisSize.min,
              //               mainAxisAlignment: MainAxisAlignment.center,
              //               crossAxisAlignment: CrossAxisAlignment.center,
              //               children: [
              //                 SizedBox(
              //                   width: 54,
              //                   height: 20,
              //                   child: Text(
              //                     '9:41',
              //                     textAlign: TextAlign.center,
              //                     style: TextStyle(
              //                       color: Color(0xFF010101),
              //                       fontSize: 17,
              //                       fontFamily: 'SF Pro Text',
              //                       fontWeight: FontWeight.w600,
              //                       height: 0.08,
              //                       letterSpacing: -0.41,
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //         Positioned(
              //           left: 318,
              //           top: 19,
              //           child: Container(
              //             width: 77.40,
              //             height: 13,
              //             child: Stack(
              //               children: [
              //                 Positioned(
              //                   left: 50,
              //                   top: 0,
              //                   child: Container(
              //                     width: 27.40,
              //                     height: 13,
              //                     child: Stack(children: [
                                  
              //                     ]),
              //                   ),
              //                 ),
              //                 Positioned(
              //                   left: 26,
              //                   top: 1,
              //                   child: Container(
              //                     width: 17,
              //                     height: 12,
              //                     decoration: BoxDecoration(
              //                       image: DecorationImage(
              //                         image: NetworkImage("https://via.placeholder.com/17x12"),
              //                         fit: BoxFit.fill,
              //                       ),
              //                     ),
              //                   ),
              //                 ),
              //               ],
              //             ),
              //           ),
              //         ),
              //       ],
              //     ),
              //   ),
              // ), */