import 'package:flutter/material.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk_flutter.dart';
import 'package:voxpollui/boarding/boarding_bes.dart';
import 'package:voxpollui/interestpage.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/

class BoardinDort extends StatefulWidget {
  final String userId;

  BoardinDort({Key? key, required this.userId}) : super(key: key);

  @override
  _StateBoardinDort createState() => _StateBoardinDort();
}

class _StateBoardinDort extends State<BoardinDort> {

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _surnameController = TextEditingController();
  final TextEditingController _birthDateController = TextEditingController();
  final TextEditingController _cityController = TextEditingController();
  final TextEditingController _districtController = TextEditingController();
  String _gender = 'Erkek'; // Varsayılan cinsiyet
  @override
  Widget build(BuildContext context) {
    Future<void> _saveDetails() async {
    final ParseUser? currentUser = await ParseUser.currentUser() as ParseUser?;
    if (currentUser == null) {
      // Handle the case where there is no logged-in user
      print("No current user found");
      return;
    }

    currentUser
      ..set('name', _nameController.text.trim())
      ..set('surname', _surnameController.text.trim())
      ..set('birthDate', _birthDateController.text.trim())
      ..set('city', _cityController.text.trim())
      ..set('district', _districtController.text.trim())
      ..set('gender', _gender);

    final response = await currentUser.update();

    if (response.success) {
      Navigator.push(context, MaterialPageRoute(builder: (context) => BoardinBes(userId: currentUser.objectId!)));
    } else {
      // Show error message
      print("Failed to update user: ${response.error}");
    }
  }
  return Scaffold(
  body: Padding(
    padding: EdgeInsets.all(16.0),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        SizedBox(height: 50,),
        Text(
          'Kişisel Bilgiler',
          style: TextStyle(
          color: Color(0xFF0C0C0C),
          fontSize: 40,
          fontFamily: 'Gilroy',
          fontWeight: FontWeight.w600,
          height: 0,
          ),
        ),
        SizedBox(height: 20,),
        Text(
          '*Bazı bilgiler sonradan değiştirilemez. Doğru girdiğinizden emin olun.',
          style: TextStyle(
            color: Colors.black,
            fontSize: 14,
          ),
        ),
        SizedBox(height: 16),
        TextField(
          decoration: InputDecoration(
            labelText: 'İsim',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'Soyisim',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'Kullanıcı Adı',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'E-Mail',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'Doğum Tarihi',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'İl',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'İlçe',
            border: UnderlineInputBorder(),
          ),
        ),
        TextField(
          decoration: InputDecoration(
            labelText: 'Cinsiyet',
            border: UnderlineInputBorder(),
          ),
        ),
        SizedBox(height: 16),
        GestureDetector(
          onTap: () {
            _saveDetails();
          },
          child: Container(
            alignment: Alignment.bottomCenter,
            width: double.infinity,
            height: 49,
            margin: EdgeInsets.all(31), // Burası ekranın kenar boşluklarını ayarlar
            decoration: ShapeDecoration(
              color: Color(0xFF2355FF),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(5),
              ),
            ),
            child: Center(
              child: Text(
                'İleri',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 16,
                  fontFamily: 'Gilroy',
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ),
        ),
      ],
    ),
  ),
);
  }
}

// class PersonalInformation extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 428,
//           height: 926,
//           clipBehavior: Clip.antiAlias,
//           decoration: ShapeDecoration(
//             color: Colors.white,
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(32),
//             ),
//           ),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 31,
//                 top: 299,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 443,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 512,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 369,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 582,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 653,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 722,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 792,
//                 child: Container(
//                   width: 366,
//                   height: 1,
//                   decoration: BoxDecoration(color: Color(0xFF0C0C0C)),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 277,
//                 child: SizedBox(
//                   width: 35,
//                   height: 25,
//                   child: Text(
//                     'İsim',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 418,
//                 child: SizedBox(
//                   width: 104,
//                   height: 26,
//                   child: Text(
//                     'Kullanıcı Adı',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 487,
//                 child: SizedBox(
//                   width: 115,
//                   height: 25,
//                   child: Text(
//                     'Doğum Tarihi',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 558,
//                 child: SizedBox(
//                   width: 54,
//                   height: 25,
//                   child: Text(
//                     'E-Mail',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 348,
//                 child: SizedBox(
//                   width: 67,
//                   height: 25,
//                   child: Text(
//                     'Soyisim',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 625,
//                 child: SizedBox(
//                   width: 9,
//                   height: 25,
//                   child: Text(
//                     'İl',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 695,
//                 child: SizedBox(
//                   width: 30,
//                   height: 25,
//                   child: Text(
//                     'İlçe',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 767,
//                 child: SizedBox(
//                   width: 69,
//                   height: 26,
//                   child: Text(
//                     'Cinsiyet',
//                     style: TextStyle(
//                       color: Color(0xFF0C0C0C),
//                       fontSize: 16,
//                       fontFamily: 'Gilroy',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 133,
//                 child: Text(
//                   'Kişisel Bilgiler',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 40,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w600,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 196,
//                 child: Text(
//                   '*Bazı bilgiler sonradan değiştirilemez.\nDoğru girdiğinizden emin olun.',
//                   style: TextStyle(
//                     color: Color(0xFF0C0C0C),
//                     fontSize: 14,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w400,
//                     height: 0.07,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 0,
//                 top: 0,
//                 child: Container(
//                   width: 428,
//                   height: 47,
//                   clipBehavior: Clip.antiAlias,
//                   decoration: BoxDecoration(),
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 33,
//                         top: 14,
//                         child: Container(
//                           width: 54,
//                           height: 21,
//                           padding: const EdgeInsets.only(top: 1),
//                           decoration: ShapeDecoration(
//                             shape: RoundedRectangleBorder(
//                               borderRadius: BorderRadius.circular(24),
//                             ),
//                           ),
//                           child: Row(
//                             mainAxisSize: MainAxisSize.min,
//                             mainAxisAlignment: MainAxisAlignment.center,
//                             crossAxisAlignment: CrossAxisAlignment.center,
//                             children: [
//                               SizedBox(
//                                 width: 54,
//                                 height: 20,
//                                 child: Text(
//                                   '9:41',
//                                   textAlign: TextAlign.center,
//                                   style: TextStyle(
//                                     color: Color(0xFF010101),
//                                     fontSize: 17,
//                                     fontFamily: 'SF Pro Text',
//                                     fontWeight: FontWeight.w600,
//                                     height: 0.08,
//                                     letterSpacing: -0.41,
//                                   ),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                       Positioned(
//                         left: 318,
//                         top: 19,
//                         child: Container(
//                           width: 77.40,
//                           height: 13,
//                           child: Stack(
//                             children: [
//                               Positioned(
//                                 left: 50,
//                                 top: 0,
//                                 child: Container(
//                                   width: 27.40,
//                                   height: 13,
//                                   child: Stack(children: [
                                  
//                                   ]),
//                                 ),
//                               ),
//                               Positioned(
//                                 left: 26,
//                                 top: 1,
//                                 child: Container(
//                                   width: 17,
//                                   height: 12,
//                                   decoration: BoxDecoration(
//                                     image: DecorationImage(
//                                       image: NetworkImage("https://via.placeholder.com/17x12"),
//                                       fit: BoxFit.fill,
//                                     ),
//                                   ),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 31,
//                 top: 843,
//                 child: Container(
//                   width: 366,
//                   height: 49,
//                   decoration: ShapeDecoration(
//                     color: Color(0xFF2355FF),
//                     shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 202,
//                 top: 861,
//                 child: Text(
//                   'İleri',
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 16,
//                     fontFamily: 'Gilroy',
//                     fontWeight: FontWeight.w700,
//                     height: 0,
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }